#We need to guess the random number generated by computer 
#if the number we guessed is lesser than the number , it should tell less
#if the number we guessed is greater than the number , it should tell high
import random

def guess_number(x):
    number=int(random.randrange(1,x))
    print(number)
    guessed_number=0
    while guessed_number!=number:
        guessed_number = int(input("Guess the number :"))
        if guessed_number>number:  
            print("number is high. Guess again")
        elif guessed_number<number: 
            print("number is less. Guess again")
    print("You guessed correct")

guess_number(10)