import random

#We need to guess the random number generated by computer 
#if the number we guessed is lesser than the number , it should tell less
#if the number we guessed is greater than the number , it should tell high
def guess_number(x):
    number=int(random.randrange(1,x))
    print(number)
    guessed_number=0
    while guessed_number!=number:
        guessed_number = int(input(f"Guess the number between 1 and {x}:"))
        if guessed_number>number:  
            print("number is high. Guess again")
        elif guessed_number<number: 
            print("number is less. Guess again")
    print("You guessed correct")

guess_number(10)

#We will pick a number and give options to computer to guess
#if the guessed number is lesser than the number , we should tell l
#if the guessed number is greater than the number , we should tell h
def computer_guess(x):
    high = x
    low = 0
    feedback=''
    while feedback!='c':
        if(low!=high):
            guess = random.randint(low,high)
        else:
            guess=low
        feedback=input(f"Number guessed is {guess}, Feedback is h or l or c ?")
        if feedback=="h":
            high=guess
        elif feedback=="l":
            low=guess
        
    print("Correct")

computer_guess(20)